### ISSUE TITLE
Help to add extra python packages to the ariflow container

### ISSUE THREAD

**Issue by emerson131** [bitnami/bitnami-docker-airflow-worker#5] opened 2020-07-22 19:39 UTC
Hi.

Im looking to add extra python packages via pip onto the airflow containers. Going by the architecture im assuming that in order for my tasks to run, i will need to add these packages on the airflow worker container. In the docker file for the airflow-webserver container i can see a run.sh file that looks for the requirements file in order to install these dependencies. However i can see no such entry for the worker and hence i cant see a mechanism that lets me add these packages when i start up the container.

Woudl appreciate some guidance on how i can get this done since i would ideally want the packages installed when my container first starts up instead of installing it via exec

Thanks
Emerson

**Comment by joancafom** [comment] 2020-07-24 13:25
Hi @emerson131 ,

It is true that `bitnami-airflow-worker` does not have this feature. I am going to investigate a little bit more about it so as to know if there is a reason behind this. On the meantime, you can resort to a custom `run.sh` script in which you provide with your desired modifications. Here is an example on how you can do this:

1. Copy the current `run.sh` to a directory of your own:

```console
$ git clone https://github.com/bitnami/bitnami-docker-airflow-worker.git
Cloning into 'bitnami-docker-airflow-worker'...
$ cd bitnami-docker-airflow-worker && mkdir customRun
$ cp 1/debian-10/rootfs/run.sh customRun/
```

2. Add the desired modifications to this file:

```diff
#!/bin/bash

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

USER=airflow
DAEMON=airflow
EXEC=$(which $DAEMON)
START_COMMAND="${EXEC} worker ${AIRFLOW_QUEUE:+-q $AIRFLOW_QUEUE} | tee /opt/bitnami/airflow/logs/airflow-worker.log"

+ echo "Hi! I am a custom RUN"

echo "Waiting for db..."
```

3. Mount a this file into the container using a volume entry, overwriting the original one.

`docker-compose.yml`
```diff
airflow-worker:
    image: docker.io/bitnami/airflow-worker:1-debian-10
    environment:
    ...
    volumes:
      - airflow_worker_data:/bitnami
+     - ./run.sh:/run.sh
```

4. If you run your container, you can see the modifications already! 😄
```console
$ docker-compose up
...
airflow-worker_1     | nami    INFO  airflow-worker successfully initialized
airflow-worker_1     | INFO  ==> Starting airflow-worker...
airflow-worker_1     | Hi! I am a custom RUN
airflow-worker_1     | Waiting for db...
...
```

Hope it helps, thanks!

**Comment by emerson131** [comment] 2020-07-26 23:08
Thanks...I was toying with the idea of appending the Dockerfile but this works out better for me as well..

**Comment by joancafom** [comment] 2020-08-03 13:38
Hi @emerson131 ,

The possibility to install additional python modules was indeed a feature other user requested (see https://github.com/bitnami/bitnami-docker-airflow/issues/32) and contributed to the solution. I think of adding this as well to `airflow-worker` but do not really know how useful it could be. What do you think of it? Could you give me some use case scenarios you encountered that required to install extra dependencies in the `worker` apart from the main `webserver`? That would be nice!

Thanks very much for your issue!

**Comment by emerson131** [comment] 2020-08-03 23:07
HI @joancafom .

Im currently trying to figure out if we need the packages in the worker image. The reason i assume we would need it, is becuase since this is the component that actually runs the tasks, i would image any custom modules used as part of the tasks will need to be available..However this is just my thinking based on the architecture but will need to validate that , that is the case. Will try to use a module in my task thats not avilable by default and test out the scenario

**Comment by joancafom** [comment] 2020-08-04 20:08
Okay @emerson131 thanks for your issue! As this workaround works for now I would leave this approach and you can come back with any further findings, we will be more than happy to evaluate it ! 😄

**Comment by wslulciuc** [comment] 2020-08-05 17:52
@joancafom I can confirm that you do need to install any external python packages on the `worker` container for a task to run. Is the recommended work around still to copy / modify `run.sh`, then mount the script? I'm using the [`bitnami/airflow`](https://github.com/bitnami/charts/tree/master/bitnami/airflow) helm chart for deployment on kubenetes and mount the `requirements.txt` using `extraVolumeMounts` and `extraVolumes` (which makes sense) on each container. But, I'd be great if I didn't have to keep a modified copy `run.sh` to mount :)

/cc @emerson131

**Comment by wslulciuc** [comment] 2020-08-05 21:10
@joancafom The `run.sh` override works great locally when using `docker-compose`, but when deploying to kubenetes with the [`bitnami/airflow`](https://github.com/bitnami/charts/tree/master/bitnami/airflow) the script can't be executed because of a permissions issue:

```
nami    INFO  Initializing airflow-scheduler
airflow INFO  ==> No injected configuration files found. Creating default config file...
airflow INFO  ==> Disabling examples...
airflow INFO  ==> Configuring Airflow database...
airflow INFO  ==> Setting Airflow Fernet key...
airflow INFO  ==> Configuring Airflow Celery Executor...
airflow INFO  ==> Deploying Airflow from scratch...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at dev-usw2-datakin0.ccalv53cdejl.us-west-2.rds.amazonaws.com:5432
postgre INFO  PostgreSQL server listening and working at dev-usw2-datakin0.ccalv53cdejl.us-west-2.rds.amazonaws.com:5432
airflow INFO  ==> Waiting for Airflow Webserver host...
airflow INFO  ==> Waiting for Redis host...
airflow INFO
airflow INFO  ########################################################################
airflow INFO   Installation parameters for airflow-scheduler:
airflow INFO     Webserver URL: airflow:8080
airflow INFO   This installation requires no credentials.
airflow INFO  ########################################################################
airflow INFO
nami    INFO  airflow-scheduler successfully initialized
INFO  ==> Starting airflow-scheduler...
[FATAL tini (45)] exec /run.sh failed: Permission denied
```

**Comment by wslulciuc** [comment] 2020-08-05 21:16
@joancafom The `run.sh` override works great locally when using `docker-compose`, but when deploying to kubenetes with the [`bitnami/airflow`](https://github.com/bitnami/charts/tree/master/bitnami/airflow) the script can't be executed because of a permissions issue:

```
nami    INFO  Initializing airflow-scheduler
airflow INFO  ==> No injected configuration files found. Creating default config file...
airflow INFO  ==> Disabling examples...
airflow INFO  ==> Configuring Airflow database...
airflow INFO  ==> Setting Airflow Fernet key...
airflow INFO  ==> Configuring Airflow Celery Executor...
airflow INFO  ==> Deploying Airflow from scratch...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at X
postgre INFO  PostgreSQL server listening and working at X
airflow INFO  ==> Waiting for Airflow Webserver host...
airflow INFO  ==> Waiting for Redis host...
airflow INFO
airflow INFO  ########################################################################
airflow INFO   Installation parameters for airflow-scheduler:
airflow INFO     Webserver URL: airflow:8080
airflow INFO   This installation requires no credentials.
airflow INFO  ########################################################################
airflow INFO
nami    INFO  airflow-scheduler successfully initialized
INFO  ==> Starting airflow-scheduler...
[FATAL tini (45)] exec /run.sh failed: Permission denied
```

**Comment by emerson131** [comment] 2020-08-05 23:12
@wslulciuc to be honest i had written an automated process to build my images based on the files in github and upload to ecr with my customised run.sh already part of the image build so i never really got that issue.

**Comment by wslulciuc** [comment] 2020-08-05 23:24
@emerson131 Yeah, I had initially considered building my own images. But, it felt like a workaround given the `run.sh`. I't may not be the worse things to have images that contain all the dependencies needed to run the DAGs.

**Comment by emerson131** [comment] 2020-08-05 23:30
@wslulciuc i agree. I would ideally want to not make any changes and the requirements.txt would be a good feature to have.

**Comment by wslulciuc** [comment] 2020-08-06 00:03
@joancafom Would it be possible to add support for a `requirements.txt` in `run.sh` similar to https://github.com/bitnami/bitnami-docker-airflow/pull/33?

**Comment by joancafom** [comment] 2020-08-07 11:16
Hi @emerson131 and @wslulciuc 

Yes, I can handle a PR in order to add support for extra python modules 😁. I will link back to this issue once done.

Thanks

**Comment by wslulciuc** [comment] 2020-08-07 14:59
Thanks, @joancafom! Can we also update `run.sh` for [`bitnami-docker-airflow-scheduler`](https://github.com/bitnami/bitnami-docker-airflow-scheduler)? DAGs fail to load / be scheduled without the extra python module installed.

**Comment by pablobmc** [comment] 2020-08-07 21:38
you can use PythonVirtualenvOperator to execute python functions with extra packages
your_task= PythonVirtualenvOperator(
    task_id='your_task_id',
    python_callable=yourFunction,
    requirements=[
        "numpy",
        "pandas==1.0.4", #or any package
    ],
    python_version='3.6',
    system_site_packages=False,
    dag=dag
)

**Comment by joancafom** [comment] 2020-08-11 11:06
Hi @emerson131 @wslulciuc 

I have implemented the changes and they will be released soon for `airflow-worker`. Could you please open a new issue in the https://github.com/bitnami/bitnami-docker-airflow-scheduler repo so as to handle/discuss it there?

Also, it would be nice if you give a try to the workaround @pablobmc provided 😄

Thanks all of you!

**Comment by emerson131** [comment] 2020-08-11 21:12
Hi @joancafom 

I’ve raised an issue for the scheduler as well. With regards to the work around , I do believe it will work, however it is still a workaround and does not answer the need to have a simple mechanism to have airflow up and running with all my requirements when I do a simple docker run. Creating a dag  to achieve this takes me off course of keeping my app deployment and code deployment separate.😔

**Comment by joancafom** [comment] 2020-08-12 07:29
Hi @emerson131 

I saw you have successfully created issue https://github.com/bitnami/bitnami-docker-airflow-scheduler/issues/5 😄 Yes, the aforementioned workaround seems to work, but I think it would reasonable if we add this feature to the `scheduler` as well. By the way, I am happy to inform you that latest release 7cb144d already implements the changes in `worker`🎉

Thanks for your issue!

**Comment by wslulciuc** [comment] 2020-08-13 22:24
@joancafom, I tested the latest worker release (`1.10.11-debian-10-r20`) and it works great!

**Comment by joancafom** [comment] 2020-08-14 06:38
Glad to hear that! I am closing this now as it seems to be resolved 😁 If you have any other issue, please do not hesitate to reach out to us again.

Thanks!

**Closed by joancafom** 2020-08-14 06:38 UTC

**Comment by emerson131** [comment] 2020-08-14 07:02
Thanks for your help @joancafom
